Description: >
  Simon Gineiger
  Udacity DevOps Nanodegree Capstone Project
  EKS Node Group Creation

Parameters:

  EnvironmentName:
    Description: The environment name that will be prefixed to resource names
    Type: String

  Subnet1:
    Description: First Subnet to deploy cluster to
    Type: String
    Default: "subnet-8034cccc" # eu-central-1c

  Subnet2:
    Description: Second Subnet to deploy cluster to
    Type: String
    Default: "subnet-b32dd8cf" # eu-central-1b

Resources:

  EKSnodegroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Sub "${EnvironmentName}-Cluster"
      NodeRole: "arn:aws:iam::370570694189:role/EKS--nodeInstanceRole"
      Subnets:
        - !Sub "${Subnet1}"
        - !Sub "${Subnet2}"
      ScalingConfig:
        MinSize: 2
        DesiredSize: 2
        MaxSize: 4