apiVersion: apps/v1
kind: Deployment
metadata:
  name: xclapi-deployment
  labels:
    app: xclapi
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: xclapi
  template:
    metadata:
      labels:
        app: xclapi
    spec:
      containers:
      - name: xclapi
        image: simongineiger/udacity-devops-capstone
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
